trigger:
  name: Retrieve and Build Images
  identifier: retrieve_and_build_images
  description: "Scheduled trigger to retrieve and build Harness CI images"
  enabled: true
  tags:
    created_by: Terraform
    role: harness-ci-image-factory
    type: scheduled
  
  # Cron scheduled trigger
  source:
    type: Scheduled
    spec:
      type: Cron
      spec:
        expression: ${SCHEDULE}
        timeZone: UTC
  
  # Pipeline inputs to be filled automatically
  inputYaml: |
    pipeline:
      identifier: harness_ci_image_factory
      variables:
        - name: registry
          type: String
          value: ${REGISTRY_NAME}
        - name: is_retry
          type: String
          value: "false" 