trigger:
  name: Harness ECR Registry Poll Trigger
  identifier: harness_ecr_registry_poll_trigger
  description: Polls public.ecr.aws/harness registry for new images and runs CI Image Factory
  enabled: true
  tags:
    created_by: Terraform
    role: harness-ci-image-factory
  
  # Cron scheduled polling trigger
  cron:
    expression: ${SCHEDULE}  # Default is "0 */6 * * *" (every 6 hours)
    timeZone: UTC
  
  # Pipeline inputs to be filled automatically
  pipelineInputs:
    pipeline:
      identifier: ${PIPELINE_ID}
      variables:
        - name: registry
          value: ${REGISTRY_NAME}
        - name: is_retry
          value: "false"
        - name: modify_default
          value: ${MODIFY_DEFAULT}
  
  # Condition to process only new Harness images
  condition:
    # We'll use a webhook condition here that will be triggered by an ECR watcher service
    # This could be implemented with AWS EventBridge or a Lambda function
    # Since this is a polling trigger, we're using cron, but a real implementation would use webhooks
    when: true
  
  # Additional metadata for logging and debugging
  source:
    name: "ECR Public Registry"
    type: "Scheduled Poll"
    scope: "harness-ci-images" 