# Default values for harness-ci-factory
# This file contains only non-sensitive default values

# Global settings
global:
  # Harness platform settings
  harness:
    platformUrl: "https://app.harness.io/gateway"
    # Secret values should be supplied in a separate secrets file
    # secrets section is intentionally empty in default values
    secrets: {}
  
  # Organization and project settings
  organization:
    name: "CI Factory"
    create: true
  
  project:
    name: "Image Management"
    create: true
  
  # Registry settings for CI images
  containerRegistry:
    type: "docker" # Supported: docker, azure
  
  # Kubernetes connector
  kubernetes:
    namespace: "harness-delegate"

# RSS Monitor settings
rssMonitor:
  # Enable or disable the RSS monitor
  enabled: true
  
  # Deployment settings
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
  # Configuration settings
  config:
    # Check interval in minutes
    checkInterval: 60
    # Debug mode
    debug: false
    # List of target images to monitor
    targetImages:
      - "harness/ci-addon"
      - "harness/ci-lite-engine"
      - "harness/drone-git"
  
  # Service account settings
  serviceAccount:
    create: true
    name: "harness-rss-monitor"

# Terraform settings (for provisioning Harness resources)
terraform:
  # Enable or disable the Terraform job
  enabled: true

  # Job settings
  job:
    # Terraform action to perform
    action: "apply" # "apply" or "destroy"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  
  # Terraform variables
  variables:
    # Maximum number of simultaneous builds to perform
    maxBuildConcurrency: 5
    # Enable schedule for pipeline execution
    enableSchedule: true
    # Schedule for pipeline execution (cron format)
    schedule: "0 2 * * *"
    # Update default image configuration
    modifyDefaultImageConfig: true

# Triggers configuration  
triggers:
  # Enable the ECR polling trigger
  ecrPolling:
    enabled: true
    # Polling schedule (6 hours by default)
    schedule: "0 */6 * * *"
  
  # Enable RSS webhook trigger
  rssWebhook:
    enabled: true 