# Default values for harness-ci-factory
# This file contains only non-sensitive default values

# Global settings
global:
  # Harness platform settings
  harness:
    platformUrl: "https://app.harness.io/gateway"
    organizationId: "default"
    projectId: "playground"
    # Secret values should be supplied in a separate secrets file
    # secrets section is intentionally empty in default values
    secrets: {}
  
  # Registry settings for CI images
  containerRegistry:
    type: "docker" # Supported: docker, azure
    name: "docker.io/myorganization"
    connectorRef: "dockerhub"
  
  # Kubernetes connector
  kubernetes:
    namespace: "harness-delegate"
    connectorRef: "kubernetes-delegate"

# RSS Monitor settings
rssMonitor:
  # Enable or disable the RSS monitor
  enabled: true
  
  # Deployment settings
  deployment:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
  # Configuration settings
  config:
    # Check interval in minutes
    checkInterval: "15"
    # Debug mode
    debug: "true"
    # List of target images to monitor
    targetImages: "harness/ci-manager,harness/ci-service,harness/drone-git,harness/drone-runner"
  
  # Service account settings
  serviceAccount:
    create: true
    name: ""

  # Test mode settings
  testMode:
    enabled: false # Set to true to run in self-test mode with mocked feed

  # Liveness probe settings
  livenessProbe:
    enabled: true
    schedule: "0 */6 * * *"  # Run every 6 hours
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 5
    nodeSelector: {}

# Terraform settings (for provisioning Harness resources)
terraform:
  # Enable or disable the Terraform job
  enabled: true

  # Job settings
  job:
    # Terraform action to perform
    action: "apply" # "apply" or "destroy"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  
  # Terraform variables
  variables:
    # Maximum number of simultaneous builds to perform
    maxBuildConcurrency: 5
    # Enable schedule for pipeline execution
    enableSchedule: true
    # Schedule for pipeline execution (cron format)
    schedule: "0 2 * * *"
    # Update default image configuration
    modifyDefaultImageConfig: true

# Triggers configuration  
triggers:
  # Enable the ECR polling trigger
  ecrPolling:
    enabled: true
    # Polling schedule (6 hours by default)
    schedule: "0 */6 * * *"
  
  # Enable RSS webhook trigger
  rssWebhook:
    enabled: true

