{{- if .Values.terraform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-terraform-templates
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-terraform-templates
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Pipeline templates
  "templates.pipelines.harness-ci-image-factory.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Template
    spec:
      type: Pipeline
      description: "Factory pipeline for building and pushing Harness CI images"
      template:
        # Simplified sample pipeline content
        pipeline:
          identifier: harness-ci-image-factory
          name: Harness CI Image Factory
          templateRef: null
          stages:
            - stage:
                name: "Find and build CI images"
                identifier: find-and-build
                type: CI
                # Additional details would follow

  "templates.pipelines.harness-ci-image-reset.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Template
    spec:
      type: Pipeline
      description: "Reset pipeline for resetting Harness CI images"
      template:
        pipeline:
          identifier: harness-ci-image-reset
          name: Reset CI Images
          templateRef: null
          stages:
            - stage:
                name: "Reset CI images"
                identifier: reset-images
                type: CI
                # Additional details would follow
  
  # Stage templates
  "templates.templates.gather-harness-ci-image-list.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Template
    spec:
      type: Stage
      description: "Template for gathering Harness CI images"
      template:
        stage:
          name: "Gather Images"
          identifier: gather-images
          type: CI
          # Additional stage configuration
  
  "templates.templates.harness-ci-build-images-azure.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Template
    spec:
      type: Stage
      description: "Template for building images in Azure"
      template:
        stage:
          name: "Build for Azure"
          identifier: build-for-azure
          type: CI
          # Azure-specific configuration
  
  "templates.templates.harness-ci-build-images-docker.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Template
    spec:
      type: Stage
      description: "Template for building Docker images"
      template:
        stage:
          name: "Build for Docker"
          identifier: build-for-docker
          type: CI
          # Docker-specific configuration
  
  # Trigger templates
  "templates.triggers.retrieve-and-build-images.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Trigger
    metadata:
      name: retrieve-and-build
    spec:
      type: Scheduled
      # Schedule configuration
  
  "templates.triggers.harness-ecr-polling-trigger.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Trigger
    metadata:
      name: ecr-polling
    spec:
      type: Scheduled
      # ECR-specific polling configuration
  
  "templates.triggers.harness-image-update-trigger.yaml": |
    apiVersion: harness.io/v1beta1
    kind: Trigger
    metadata:
      name: image-update
    spec:
      type: Webhook
      # Webhook configuration
{{- end }} 